package model;
// Generated Feb 29, 2020 6:06:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name="merchant"
    ,catalog="hatkhola"
)
public class Merchant  implements java.io.Serializable {


     private Long id;
     private String name;
     private String contactNo;
     private String email;
     private String password;
     private Double share;

    public Merchant() {
    }

    public Merchant(String name, String contactNo,Double share, String email, String password) {
       this.name = name;
       this.contactNo = contactNo;
       this.share = share;
       this.email = email;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", length=120)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="contact_no", length=20)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    @Column(name="share", length=11)
    public Double getShare() {
        return share;
    }

    public void setShare(Double share) {
        this.share = share;
    }

}


